USE CURSO;

CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M','F') NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    CPF VARCHAR(15) NOT NULL UNIQUE,
    ID_ENDERECO INT NOT NULL UNIQUE,
    ID_TELEFONE INT NOT NULL
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT, 
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,

	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE_TEST(IDCLIENTE)
);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_ENDERECO
FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(IDENDERECO);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT, 
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT NOT NULL,

	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE_TEST(IDCLIENTE)
);

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_TELEFONE) REFERENCES TELEFONE(IDTELEFONE);